on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build
        run: .github/build

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            skarnet-builder/dist/*.tar.gz
            skarnet-builder/dist/*.md
            skarnet-builder/dist/*.txt

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: skarnet-builder/dist

      - name: create and upload release
        run: .github/release
        env:
          TRAVIS_REPO_SLUG: just-containers/skaware
          TRAVIS_TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

